#!/bin/bash

if [[ -z $1 ]]; then
    echo "[$DATENOW][$TIMENOW] Don't forget to add your directory as argument! ex: bash newscript myphotos"
    exit 1
fi

TIMENOW="$(date +'%H:%M:%S')"
DATENOW="$(date +'%d.%m.%Y')"
USER="$(whoami)"
GITREPO="https://github.com/perryvibes/DevOps-Projects.git"

SRCDIR="$(
    find ~ -type d -name "$1" -not -path "/home/$USER/.local/share/Thrash/*" | head -n 1
)"

DESTDIR="/home/$USER/Desktop/DevOpsProjects/BackupBashScript"


if [[ -n $SRCDIR ]]; then
    
    echo "[$DATENOW][$TIMENOW] Found directory $1!"
    mkdir -p "$DESTDIR"
    cp -r "$SRCDIR" "$DESTDIR/$1 [$DATENOW][$TIMENOW]"
    if [ $? -eq 0 ]; then # Checking if copy command went well
        echo "[$DATENOW][$TIMENOW] Files copied succesfully!"
    else 
        echo "[$DATENOW][$TIMENOW] ERROR! Cannot copy files from source directory to backup directory"
    fi

    cd "$DESTDIR" || exit 1
    
    git add "$DESTDIR/."
    git commit -m "Adding new items $DATENOW-$TIMENOW"
    git branch -M master
    git push origin master

    if [ $? -eq 0 ]; then 
        echo "[$DATENOW][$TIMENOW] Backup PUSHED to Github succesfully!"
    else
        echo "[$DATENOW][$TIMENOW] ERROR! Github PUSH failed!"
    fi

else
    echo "[$DATENOW][$TIMENOW] Directory NOT FOUND! Check for misstyping..."
fi